Rename utility Locate to Locatefile

diff --git a/locatefile/locatefile b/locatefile/locatefile
--- a/locatefile/locatefile
+++ b/locatefile/locatefile
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # 
-# Locate a file or directory from a database.
+# Locate a file or directory in a database.
 # 
 
 readonly HERE="$(dirname "${0}")"
@@ -8,10 +8,10 @@ source "${HERE}/CONFIGURATIONS.bash"
 
 printHelpMessage() {
   echo -ne "\
-locate
+locatefile
 
 Usage:
-  locate [options] <file or directory>
+  locatefile [options] <file or directory>
 
 Options:
   -o <FIND_OCCURRENCE>
@@ -25,11 +25,11 @@ while getopts :o:dh OPT; do
   case "${OPT}" in
     o)
       if [[ ! "${OPTARG}" =~ ^[0-9]+$ ]]; then
-        echo "locate: invalid value \"${OPTARG}\" for option -o" 1>&2
+        echo "locatefile: invalid value \"${OPTARG}\" for option -o" 1>&2
         exit 1
       else
         if [ -z "${OPTARG}" ]; then
-          echo 'locate: missing argument for option -o' 1>&2
+          echo 'locatefile: missing argument for option -o' 1>&2
           exit 1
         fi
         OPT_FIND_OCCUR_NO="${OPTARG}"
@@ -38,7 +38,7 @@ while getopts :o:dh OPT; do
     d) OPT_FIND_DIRECTORIES=true;;
     h) printHelpMessage; exit;;
     \?)
-      echo "locate: option \"${OPTARG}\" is unknown" 1>&2
+      echo "locatefile: option \"${OPTARG}\" is unknown" 1>&2
       exit 1
       ;;
   esac
@@ -47,7 +47,7 @@ shift $((OPTIND - 1))
 
 
 if [ $# -eq 0 ]; then
-  echo 'locate: no file name specified' 1>&2
+  echo 'locatefile: no file name specified' 1>&2
   exit 1
 fi
 
