Update option names in openurl

diff --git a/web_management/url_parsing_and_opening/openurl/openurl b/web_management/url_parsing_and_opening/openurl/openurl
--- a/web_management/url_parsing_and_opening/openurl/openurl
+++ b/web_management/url_parsing_and_opening/openurl/openurl
@@ -97,53 +97,49 @@ printHelpMessage() {
 
   echo -ne "\
 Usage:
-  openurl [options] <url alias> [search queries]
-  openurl [options] <search query for default search url>
-  openurl [options] <websites/URLs...>
-
-  First usage (examples):
-    openurl wikip history of science
-    openurl dir phoenix, az %% seattle, wa
-
-  Second usage:
-    If a URL alias is not found, all arguments
-    will be used as search queries with the default
-    search URL (this can be changed in
-    CONFIGURATIONS).
-
-  Third usage:
-    If any of the arguments begin with \"http[s]://\",
-    \"ftp://\" or \"file://\" or end with any of the top
-    level domains defined by URL_MATCH_TOP_LEVEL_DOMAINS
-    under CONFIGURATIONS, each will be openeded as a URL
-    directly.
+  1. openurl [options] <url_alias> [search_queries]
+  2. openurl [options] <search_query>
+         If a URL alias is not found, all arguments  will be
+         used as search queries with the default search URL
+         (this can be changed in CONFIGURATIONS).
+  3. openurl [options] <websites/URLs...>
+         If any of the arguments begin with \"http[s]://\",
+         \"ftp://\" or \"file://\" or end with any of the top
+         level domains defined by URL_MATCH_TOP_LEVEL_DOMAINS
+         under CONFIGURATIONS, each will be openeded as a URL
+         directly.
 
 Options:
   Argument processing:
-    -s          do not match the first argument with an
+    -s, --force-search
+                do not match the first argument with an
                 alias and instead use all arguments as
                 search queries with the default search URL
-    -a          match the first N arguments as aliases and
-                use all arguments after the last matching
-                alias as search queries
+    -m, --multiple-aliases
+                match each consecutive argument as an alias until the last one
+                is found and use the remaining arguments as search queries
+
   Output processing:
-    -g<1-9>  -<1-9>
+    -g<1-9>, --gui<1-9> 
                 open in the GUI browser of the given number
-    -t<1-7>     open in the terminal browser of the given
+    -t<1-7>, --term<1-7>
+                open in the terminal browser of the given
                 number
-    -d  -dump[+NUM_PAGES]
+    -d, -dump[+NUM_PAGES]
                 dump the output of each URL to a terminal
                 window (using terminal browser 1 by
                 default); optionally jump forward the
                 given number of pages
-    -c          copy all URLs to the X11 clipboard and do
-                not run anything
+    -c, --clipboard
+                output all URLs to the X11 clipboard and run
+                nothing
+
   Other:
-    -l  --list    list current browser commands
-    -h  --help    show help message
+    -l, --list    list current browser commands
+    -h, --help    show help message
 
 Notes:
-  Search queries are delimited with \"%%\".
+  Search queries are delimited by \"%%\".
   
   Using any of the browser type or the dump
   option(s) will override all alias and URL
@@ -156,7 +152,7 @@ Notes:
 }
 
 listBrowserCommands() {
-  local msg='openurl: Current browser commands:'
+  local msg='Openurl current browser commands:'
   for i in {1..9}; do
     local brwsrVar="BROWSER_GUI${i}"
     local browser="${!brwsrVar}"
@@ -202,7 +198,7 @@ printBrowserVariableNotDefinedMessage() {
 }
 
 # ============================================
-#   Initialization
+#   Initialize main variables
 # ============================================
 
 # DEFAULT/ALIAS CONFIGURATIONS (Assigned by either argument or alias/URL
@@ -211,7 +207,7 @@ printBrowserVariableNotDefinedMessage() {
 # everytime a URL is opened unless changed by argument or alias/URL
 # configuration options).
 
-# Initial/default browser
+# Default browser
 BROWSER="${BROWSER_GUI1}"
 # Whether or not to dump the page (it is likely not preferrable to set this to
 # true by default)
@@ -226,33 +222,35 @@ BROWSER_TYPE='GUI' # 'GUI' or 'TERM'; change accordingly if initial/default
                    # browser is changed.
 
 # ============================================
-#   Options and arguments
+#   Process options and arguments
 # ============================================
 
-OPTS="$(getopt -a -o 1,2,3,4,5,6,7,8,9,d::,s,a,c,l,h --long g1,g2,g3,g4,g5,g6 \
-    --long g7,g8,g9,t1,t2,t3,t4,t5,t6,t7,list,help -n 'openurl' -- \
-    "${@}")"
+OPTS="$(getopt -a -o d::,s,m,c,l,h --long gui1,gui2,gui3,gui4,gui5,gui6,gui7 \
+    --long gui8,gui9,g1,g2,g3,g4,g5,g6,g7,g8,g9,term1,term2,term3,term4,term5 \
+    --long term6,term7,t1,t2,t3,t4,t5,t6,t7,force-search,multiple-aliases \
+    --long clipboard,list,help -n 'openurl' -- "${@}")"
 [ "$?" -ne 0 ] && exit 1
-eval set -- "${OPTS}" 
+eval set -- "${OPTS}"
 
 while true; do
   case "${1}" in
-    --g?|-1|-2|-3|-4|-5|-6|-7|-8|-9)
-        [[ "${1}" = '--g'* ]] && brwsrNum="${1:3}" || brwsrNum="${1:1}"
+    --gui?|--g?)
+        [ -z "${1##'--gui'*}" ] && brwsrNum="${1:5}" || brwsrNum="${1:3}"
         brwsrVar="BROWSER_GUI${brwsrNum}"
         BROWSER="${!brwsrVar}"
         BROWSER_TYPE='GUI'
         CONFIG_OPT_SET=true
         ;;
-    --t?)
-        brwsrNum="${1:3}"
+    --term?|--t?)
+        [ -z "${1##'--term'*}" ] && brwsrNum="${1:6}" || brwsrNum="${1:3}"
         brwsrVar="BROWSER_TERM${brwsrNum}"
         BROWSER="${!brwsrVar}"
         BROWSER_TYPE='TERM'
         CONFIG_OPT_SET=true
         ;;
-    -d|-dump)
-        DUMP=true; CONFIG_OPT_SET=true
+    -dump|-d)
+        DUMP=true
+        CONFIG_OPT_SET=true
         if [ -n "${2}" ]; then
           arg="${2}"
           [[ "${arg}" = 'ump'* ]] && arg="${arg#'ump'}"
@@ -264,9 +262,9 @@ while true; do
         fi
         shift
         ;;
-    -s) OPT_OVERRIDE_ALIAS_MATCHING=true;;
-    -a) OPT_USE_ALL_ARGS_FOR_ALIASES=true;;
-    -c) OPT_OUTPUT_URLS_TO_X11_CLIPBOARD=true;;
+    --force-search|-s) OPT_FORCE_SEARCH=true;;
+    --multiple-aliases|-m) OPT_MULTIPLE_ALIASES=true;;
+    --clipboard|-c) OPT_OUTPUT_TO_CLIPBOARD=true;;
     --list|-l) listBrowserCommands; exit;;
     --help|-h) printHelpMessage full; exit;;
     --) shift; break;;
@@ -280,13 +278,13 @@ if [ "$#" -eq 0 ] && [ "${DUMP}" = 'true' ]; then
   exit 1
 fi
 
-if [ "${OPT_USE_ALL_ARGS_FOR_ALIASES}" = 'true' ]; then
-  if [ "${OPT_OVERRIDE_ALIAS_MATCHING}" = 'true' ]; then
-    echo 'openurl: cannot use options -s and -a together' 1>&2
+if [ "${OPT_MULTIPLE_ALIASES}" = 'true' ]; then
+  if [ "${OPT_FORCE_SEARCH}" = 'true' ]; then
+    echo 'openurl: cannot use options -s and -m together' 1>&2
     exit 1
   fi
   if [ $# -eq 0 ]; then
-    echo -e 'openurl: one or more aliases required\n  with option -a' 1>&2
+    echo -e 'openurl: one or more aliases required\n  with option -m' 1>&2
     exit 1
   fi
 fi
@@ -302,7 +300,7 @@ if [ "${DUMP}" = 'true' ] && [ "${BROWSER_TYPE}" = 'GUI' ]; then
 fi
 
 # ============================================
-#   Prerequisites
+#   Check prerequisites
 # ============================================
 
 for urlAliasesFile in "${URL_ALIASES_FILES[@]}"; do
@@ -315,7 +313,7 @@ for urlAliasesFile in "${URL_ALIASES_FILES[@]}"; do
 done
 
 # ============================================
-#   Main functions
+#   Create main functions
 # ============================================
 
 # processAliasConfigurations:
@@ -466,7 +464,7 @@ finalizeConfigurationsAndExecuteBrowser() {
 }
 
 # ===================================================
-#   Open all URL arguments and exit if any are.
+#   Open all URL arguments and exit if any are
 # ===================================================
 
 topLevlDomnsRegx="$(echo "${URL_MATCH_TOP_LEVEL_DOMAINS}" | tr -s ' ')"
@@ -489,7 +487,7 @@ URLS_FOR_DIRECT_OPEN=($(echo "${@}" | perl -ne "
 "))
 
 if [ "${#URLS_FOR_DIRECT_OPEN[@]}" -ge 1 ]; then
-  if [ "${OPT_OUTPUT_URLS_TO_X11_CLIPBOARD}" = 'true' ]; then
+  if [ "${OPT_OUTPUT_TO_CLIPBOARD}" = 'true' ]; then
     echo -e 'openurl: option -c not allowed when opening URLs directly' 1>&2
     exit 1
   fi
@@ -500,7 +498,7 @@ if [ "${#URLS_FOR_DIRECT_OPEN[@]}" -ge 1 ]; then
 fi
 
 # ===================================================
-#   Get and parse all URLs for one or more alias(es) if the alias(es) exist(s).
+#   Get and parse all URLs for one or more alias(es) if the alias(es) exist(s)
 # ===================================================
 
 # Argument cases:
@@ -511,14 +509,14 @@ fi
 #     arguments as one or more search queries with the default search URL
 #     otherwise and if the respective configuration is set respectively.
 # 
-#   All arguments used as aliases (switch -a):
+#   All arguments used as aliases (switch -m):
 #     Use each argument after the first as an alias until no more aliases are
 #     found and use all remaining arguments as one or more search queries for
 #     the aliases URLs if the first argument is a found alias. Print a message
 #     and exit otherwise.
 
-if [ -z "${OPT_OVERRIDE_ALIAS_MATCHING}" ]; then
-  if [ "${OPT_USE_ALL_ARGS_FOR_ALIASES}" = 'true' ]; then
+if [ -z "${OPT_FORCE_SEARCH}" ]; then
+  if [ "${OPT_MULTIPLE_ALIASES}" = 'true' ]; then
     aliasesFileParserArgs="${@}"
   else
     aliasesFileParserArgs="${1}"
@@ -591,7 +589,7 @@ if [ -n "${aliasesFileParserOut}" ]; then
       setUpUrlsUrlsOptsArr '1' "${@}"
     fi
 
-    if [ "${OPT_OUTPUT_URLS_TO_X11_CLIPBOARD}" = 'true' ]; then
+    if [ "${OPT_OUTPUT_TO_CLIPBOARD}" = 'true' ]; then
       for url_urlOpts in "${URLS_URLSOPTS[@]}"; do
         url_urlOptsArr=(${url_urlOpts//'<>'/ })
         URLS_FOR_X11_CLIPBOARD+=("${url_urlOptsArr[0]}")
@@ -644,7 +642,7 @@ if [ -n "${aliasesFileParserOut}" ]; then
   done #!for each alias options and URLs
 
 else
-  if [ "${OPT_USE_ALL_ARGS_FOR_ALIASES}" = 'true' ]; then
+  if [ "${OPT_MULTIPLE_ALIASES}" = 'true' ]; then
     echo 'openurl: no aliases found'
     exit
   fi
@@ -657,7 +655,7 @@ else
   dfltSrchUrlPrsd="$("${HERE}/search-placeholder-url-parser.pl" \
       "${DEFAULT_SEARCH_URL}" "${@}")"
 
-  if [ "${OPT_OUTPUT_URLS_TO_X11_CLIPBOARD}" = 'true' ]; then
+  if [ "${OPT_OUTPUT_TO_CLIPBOARD}" = 'true' ]; then
     URLS_FOR_X11_CLIPBOARD=("${dfltSrchUrlPrsd}")
   else
     finalizeConfigurationsAndExecuteBrowser "${BROWSER}" "${BROWSER_TYPE}" \
